from time import time
import warnings
import numpy as np

from ..symmetry.sawf_kirr import get_symmetrizer_Zirr, get_symmetrizer_Uirr
from ..utility import vectorize, select_window_degen
from ..symmetry.sawf import IrrepsIncompatibleError, VoidSymmetrizer
from .wannierizer import Wannierizer


def wannierise(wandata,
               froz_min=np.inf,
               froz_max=-np.inf,
               frozen_states=[],
               outer_min=-np.inf,
               outer_max=np.inf,
               num_iter=1000,
               conv_tol=1e-9,
               num_iter_converge=3,
               mix_ratio_z=0.5,
               mix_ratio_u=1,
               print_progress_every=10,
               sitesym=False,
               check_irreps=True,
               check_irreps_warn=False,
               localise=True,
               init="amn",
               num_wann=None,
               parallel=True,
               symmetrize_Z=True,
               irreducible=False,
               print_wcc_chk=False,
               savechk=True,
               wcc_start_red=None,
               ):
    r"""
    Performs disentanglement and maximal localization of the bands recorded in wandata.
    The disentanglement is done following the procedure described in `Souza et al., PRB 2001 <https://doi.org/10.1103/PhysRevB.65.035109>`__. 
    The localization is done following a simplified procedure, avoiding gradient descent of the spread functional.

    At the end writes :attr:`wandata.chk.v_matrix` and sets :attr:`wandata.wannierised = True`

    Parameters
    ----------
    wandata : :class:`~wannierberri.WannierData`
        Input Wannier90 data container.
    froz_min, froz_max : float
        Lower and upper bounds of the frozen window.
    frozen_states : list[int] or dict[int, list[int]]
        Explicit frozen-state selection. A list applies to all k-points, while a
        dictionary maps each 0-based k-point index to a list of 0-based band indices.
    outer_min, outer_max : float
        Lower and upper bounds of the outer window.
    num_iter : int
        Maximum number of disentanglement/localization iterations.
    conv_tol : float
        Convergence tolerance for the spread functional, in :math:`\mathring{\rm A}^{2}`.
    num_iter_converge : int
        Number of printed iterations used to estimate the convergence standard deviation.
    mix_ratio_z : float
        Mixing parameter for the disentanglement `Z` matrix. `1` is fastest; smaller
        values are usually more stable.
    mix_ratio_u : float
        Mixing parameter for the localization `U` matrix. Values below `1` may help
        stability but are currently more prone to non-convergence.
    print_progress_every : int
        Frequency of progress printing.
    sitesym : bool
        Whether to enforce site symmetry. If `True`, `wandata` must contain a
        symmetrizer, either read from `pw2wannier90` or generated by WannierBerri.
    check_irreps : bool
        If `sitesym=True`, raise an error when the frozen/outer windows are incompatible
        with the selected projections.
    check_irreps_warn : bool
        If `sitesym=True`, print a warning instead of raising when the irreps are incompatible.
    localise : bool
        If `True`, perform localization in addition to disentanglement.
    init : {'amn', 'random', 'restart'}
        Initialization mode for the `U` matrix.
    num_wann : int or None
        Number of Wannier functions. Required for `init='random'` without site symmetry.
    parallel : bool
        If `True`, try to run in parallel using `ray`; otherwise run in serial mode.
    symmetrize_Z : bool
        Whether to symmetrize the disentangled `Z` matrix.
    irreducible : bool
        If `True`, keep the final gauge only on irreducible k-points in the checkpoint output.
    print_wcc_chk : bool
        If `True`, print Wannier centers and spreads after updating the checkpoint file.
    savechk : bool
        If `True`, save the updated checkpoint as ``<seedname>.chk.npz``.
    wcc_start_red : array-like or None
        Optional initial Wannier centers in reduced coordinates with shape ``(num_wann, 3)``.

    Returns
    -------
    numpy.ndarray
        Optimized ``v_matrix`` stored in ``wandata.chk.v_matrix``.


        * Also updates ``wandata.wannierised``, ``wandata.chk.wannier_centers_cart``,
            and ``wandata.chk.wannier_spreads``.
        * Disentanglement and localization are done together in a single loop.
        * If ``sitesym=True``, the optimization is carried out in the irreducible BZ and
            then symmetrized to the full BZ.
    """
    if wandata.irreducible:
        irreducible = True
    if not (mix_ratio_u == 1):
        warnings.warn(f"mix_ratio_u = {mix_ratio_u} != 1 is not tested, use with caution")

    t0 = time()
    if froz_min > froz_max:
        print("froz_min > froz_max, nothing will be frozen")
    assert 0 < mix_ratio_z <= 1
    NK = wandata.mmn.NK
    if sitesym:
        kptirr = wandata.symmetrizer.kptirr
        symmetrizer = wandata.symmetrizer
        include_k = np.zeros(NK, dtype=bool)
        neighbours = wandata.bkvec.neighbours
        for ik in kptirr:
            include_k[ik] = True
            include_k[neighbours[ik]] = True
    else:
        kptirr = np.arange(NK)
        symmetrizer = VoidSymmetrizer(NK=NK)
        include_k = np.ones(NK, dtype=bool)

    frozen = vectorize(select_window_degen, [wandata.eig.data[ik] for ik in kptirr], to_array=True,
                       kwargs=dict(win_min=froz_min, win_max=froz_max, include_degen=False))
    selected_bands = vectorize(select_window_degen, [wandata.eig.data[ik] for ik in kptirr], to_array=True,
                               kwargs=dict(win_min=outer_min, win_max=outer_max, include_degen=True))




    if isinstance(frozen_states, list):
        for ib in frozen_states:
            frozen[:, ib] = True
    elif isinstance(frozen_states, dict):
        for ik, frozen_ik in frozen_states.items():
            if ik in kptirr:
                print(f"{kptirr=}, {ik=}, {frozen_ik=}")
                iki = np.where(kptirr == ik)[0][0]
                for ib in frozen_ik:
                    frozen[iki, ib] = True

    frozen = symmetrizer.select_full_blocks(frozen, include_partial_blocks=True)
    selected_bands = symmetrizer.select_full_blocks(selected_bands, include_partial_blocks=True)
    free = vectorize(np.logical_not, frozen, to_array=True)
    deselected = vectorize(np.logical_and, np.logical_not(selected_bands), free, to_array=True)
    assert np.all(selected_bands[frozen]), "Frozen bands should be included in the selected bands"
    free[deselected] = False
    # print(f"selected_bands: \n{selected_bands} ")

    if sitesym:
        if check_irreps or check_irreps_warn:
            if wandata.symmetrizer.spacegroup.spinor:
                Warning("The check of irreps is not implemented for spinor case. Skipping the check, leaving to your responsibility")
            elif np.any([symop.time_reversal for symop in wandata.symmetrizer.spacegroup.symmetries]):
                Warning("The check of irreps is not implemented for anti-unitary symmetries. Skipping the check, leaving to your responsibility")
            else:
                try:
                    symmetrizer.check_windows(frozen=frozen, outer=selected_bands)
                except IrrepsIncompatibleError as e:
                    if check_irreps:
                        raise e
                    elif check_irreps_warn:
                        warnings.warn(str(e))



    if not wandata.has_file("chk"):
        from ..w90files.chk import CheckPoint
        wandata.set_file("chk", CheckPoint(num_kpts=NK,
                                           num_bands=wandata.mmn.NB,
                                           mp_grid=wandata.bkvec.mp_grid,
                                           kpt_red=wandata.bkvec.kpt_red,
                                           real_lattice=wandata.bkvec.real_lattice,
                                           num_wann=0),
                         allow_selected_bands=True
                                           )  # num_wann will be set later from amn


    if init == "amn":
        amn = {kpt: wandata.amn.data[kpt] for kpt in kptirr}
        wandata.chk.num_wann = wandata.amn.NW
    elif init == "random":
        if sitesym:
            num_wann = symmetrizer.num_wann
        else:
            assert num_wann is not None, "num_wann should be provided for random initialization without site-symmetry"
        rnd = np.random.random((len(kptirr), wandata.mmn.NB, num_wann, 2))
        amn = {kpt: rnd[ik, :, :, 0] + 1j * rnd[ik, :, :, 1] for ik, kpt in enumerate(kptirr)}
        del rnd
        wandata.chk.num_wann = num_wann
    elif init == "restart":
        assert wandata.wannierised, "The data is not wannierised"
        amn = {kpt: wandata.chk.v_matrix[kpt].copy() for kpt in kptirr}
    else:
        raise ValueError("init should be 'amn' or 'random'")

    if hasattr(wandata.chk, "wannier_centers_cart") and wcc_start_red is None:
        wcc_cart = wandata.chk.wannier_centers_cart
        if wcc_cart is not None:
            wcc_start_red = wcc_cart.dot(np.linalg.inv(wandata.bkvec.real_lattice))
    if wcc_start_red is not None:
        wcc_start_red = np.array(wcc_start_red, dtype=float)
    if wcc_start_red is None or wcc_start_red.shape != (wandata.chk.num_wann, 3):
        wcc_start_red = np.zeros((wandata.chk.num_wann, 3))


    neighbours_all = wandata.bkvec.neighbours
    neighbours_irreducible = np.array([[symmetrizer.kpt2kptirr[ikb] for ikb in wandata.bkvec.neighbours[ik]]
                                       for ik in kptirr])

    # wk = wandata.bkvec.wk_unique
    bk_cart = wandata.bkvec.bk_cart
    t1 = time()
    wannierizer = Wannierizer(real_lattice=wandata.bkvec.real_lattice,
                              bk_cart=bk_cart,
                              parallel=parallel, symmetrizer=symmetrizer,
                              wcc_red=wcc_start_red)

    for ik, kpt in enumerate(kptirr):
        wannierizer.add_kpoint(Mmn=wandata.mmn.data[kpt],
                            frozen=frozen[ik],
                            frozen_nb=frozen[neighbours_irreducible[ik]],
                            free=free[ik],
                            free_nb=free[neighbours_irreducible[ik]],
                            wb=wandata.bkvec.wk,
                            bk=wandata.bkvec.bk_cart,
                            symmetrizer_Zirr=get_symmetrizer_Zirr(symmetrizer, ik, free[ik]) if symmetrize_Z else VoidSymmetrizer(NK=1),
                            symmetrizer_Uirr=get_symmetrizer_Uirr(symmetrizer, ik),
                            ikirr=ik,
                            amn=amn[kpt],
                            weight=symmetrizer.ndegen(ik) / symmetrizer.NK
                            )
    t2 = time()

    # The _IR suffix is used to denote that the U matrix is defined only on k-points in the irreducible BZ
    U_opt_full_IR = wannierizer.get_U_opt_full()
    # the _BZ suffix is used to denote that the U matrix is defined on all k-points in the full BZ
    U_opt_full_BZ = symmetrizer.U_to_full_BZ(U_opt_full_IR, include_k=include_k)

    wannierizer.update_Unb_all([[U_opt_full_BZ[ib] for ib in neighbours_all[kpt]] for kpt in kptirr])

    wcc = wannierizer.wcc_cart
    spreads = wannierizer.spreads
    print_centers_and_spreads(wcc=wcc, spreads=spreads, comment="starting WFs")

    converge_list = []
    delta_std = np.inf
    t_update = 0
    t01 = time()
    for i_iter in range(num_iter):
        U_neigh = [[U_opt_full_BZ[ib] for ib in neighbours_all[kpt]] for kpt in kptirr]
        tx = time()
        U_opt_full_IR = wannierizer.update_all(U_neigh, mix_ratio=mix_ratio_z,
                                               mix_ratio_u=mix_ratio_u,
                                               localise=localise)
        t_update += time() - tx

        U_opt_full_BZ = symmetrizer.U_to_full_BZ(U_opt_full_IR, include_k=include_k)

        wcc = wannierizer.wcc_cart
        spreads = wannierizer.spreads
        converge_list.append(np.hstack((wcc, spreads[:, None])))
        delta_std = np.std(converge_list[-num_iter_converge:], axis=0).max()

        if i_iter % print_progress_every == 0:
            print_centers_and_spreads(wcc=wcc, spreads=spreads, comment=f"Iteration {i_iter} (from wannierizer)", std=delta_std)

        if i_iter > num_iter_converge and delta_std < conv_tol:
            print(f"Converged after {i_iter} iterations")
            break

    t02 = time()

    U_opt_full_BZ = symmetrizer.U_to_full_BZ(U_opt_full_IR, include_k=include_k if irreducible else None)
    print_centers_and_spreads(wcc=wcc, spreads=spreads, comment="Final state (from wannierizer)", std=delta_std)
    update_chk(wandata=wandata, U_opt_full_BZ=U_opt_full_BZ, wcc=wcc, spreads=spreads, print_wcc=print_wcc_chk)
    if not irreducible:
        wcc_chk, spreads_chk = wandata.chk.get_wannier_centers(wandata.bkvec, wandata.mmn, spreads=True)
        print_centers_and_spreads(wcc=wcc_chk, spreads=spreads_chk, comment="Final state (from chk)")
        if not np.allclose(wcc, wcc_chk, atol=1e-6):
            warnings.warn(f"The Wannier centers from the chk file and the Wannier centers from the wannierizer are not the same. diff = {np.abs(wcc - wcc_chk).max()}")
        if not np.allclose(spreads, spreads_chk, atol=1e-2):
            warnings.warn(f"The Wannier spreads from the chk file and the Wannier spreads from the wannierizer are not the same. diff = {np.abs(spreads - spreads_chk).max()}")

    # if not np.allclose(wcc, wcc_chk, atol=1e-4):
    #     warnings.warn(f"The Wannier centers from the chk file and the Wannier centers from the wannierizer are not the same. diff = {np.abs(wcc - wcc_chk).max()}")
    # if not np.allclose(spreads, spreads_chk, atol=1e-4):
    #     warnings.warn(f"The Wannier spreads from the chk file and the Wannier spreads from the wannierizer are not the same. diff = {np.abs(spreads - spreads_chk).max()}")


    wandata.wannierised = True
    print(f"time for creating wannierizer {t2 - t1}")
    print(f"time for iterations {t02 - t01}")
    print(f"time for updating {t_update}")
    print(f"total time for wannierization {time() - t0}")
    if savechk:
        chk = wandata.get_file('chk')
        chk.to_npz(wandata.seedname + ".chk")
    return wandata.chk.v_matrix




def update_chk(wandata, U_opt_full_BZ,
               wcc=None, spreads=None,
               comment="", print_wcc=False):
    """
    print the centers and spreads of the Wannier functions

    Parameters
    ----------
    wandata : WannierData
        the data (inputs of wannier90)
    U_opt_free_BZ : list of numpy.ndarray(nBfree,nW)
        the optimized U matrix for the free bands and wannier functions
    """

    wandata.chk.v_matrix = {ik: U for ik, U in enumerate(U_opt_full_BZ) if U is not None}
    if (wcc is None) or (spreads is None) or print_wcc:
        wcc_new, spreads_new = wandata.chk.get_wannier_centers(wandata.mmn, spreads=True)
        if wcc is None:
            wcc = wcc_new
        if spreads is None:
            spreads = spreads_new
    wandata.chk.wannier_centers_cart, wandata.chk.wannier_spreads = wcc, spreads
    if print_wcc:
        print_centers_and_spreads(wcc_new, spreads_new, comment=comment + ": from chk")
    return wcc, spreads


def print_centers_and_spreads(wcc, spreads, comment=None, std=None):
    """
    print the centers and spreads of the Wannier functions

    Parameters
    ----------
    wcc: np.ndarray(nW,3)
        the centers of the Wannier functions
    spreads: np.ndarray(nW,)
        the spreads of the Wannier functions
    comment: str
        the comment to print
    std: float
        the standard deviation of the spread functional over the last `num_iter_converge` iterations
    set_wcc_chk: bool
        whether to set the wcc and spreads to the chk file
    """
    breakline = "-" * 100
    startline = "#" * 100
    endline = startline
    print(startline)
    if comment is not None:
        print(comment)
        print(breakline)
    print("wannier centers and spreads")
    print(breakline)
    for w, s in zip(wcc, spreads):
        w = np.round(w, 12)
        print(f"{w[0]:16.12f}  {w[1]:16.12f}  {w[2]:16.12f}   |   {s:16.12f}")
    print(breakline)
    w = wcc.sum(axis=0)
    s = np.sum(spreads)
    print((f"{w[0]:16.12f}  {w[1]:16.12f}  {w[2]:16.12f}   |   {s:16.12f} <- sum"))
    print(f"  {' ' * 38}  maximal spread = {np.max(spreads):16.12f}")
    if std is not None:
        print(f"standard deviation = {std}")
    print(endline)


# def print_progress(i_iter, Omega_list, num_iter_converge,
#                    spread_functional=None, spreads=None,
#                    wandata=None, U_opt_full_BZ=None):
#     """
#     print the progress of the wannierisation

#     Parameters
#     ----------
#     Omega_I_list : list of float
#         the list of the spread functional
#     num_iter_converge : int
#         the number of iterations to check the convergence

#     Returns
#     -------
#     float
#         the standard deviation of the spread functional over the last `num_iter_converge` iterations
#     """

#     if spreads is None:
#         assert spread_functional is not None
#         wcc = spread_functional.get_wcc(U_opt_full_BZ)
#         spreads = spread_functional(U_opt_full_BZ, wcc=wcc)

#     Omega_list.append(spreads["Omega_tot"])
#     Omega = Omega_list[-1]
#     if i_iter > 0:
#         delta = f"{Omega - Omega_list[-2]:15.8e}"
#     else:
#         delta = "--"

#     if len(Omega_list) > num_iter_converge:
#         delta_max = np.abs(Omega_list[-num_iter_converge:] - np.mean(Omega_list[-num_iter_converge:])).max()
#         delta_max_str = f"{delta_max:15.8e}"
#         slope = (Omega_list[-1] - Omega_list[-num_iter_converge - 1]) / num_iter_converge
#         slope_str = f"{slope:15.8e}"
#     else:
#         delta_max = np.inf
#         delta_max_str = "--"
#         slope_str = "--"

#     comment = f"iteration {i_iter:4d} Omega= {Omega:15.10f}  delta={delta}, max({num_iter_converge})={delta_max_str}, slope={slope_str}"
#     print_centers_and_spreads(wandata, U_opt_full_BZ, spreads=spreads, comment=comment)
#     sys.stdout.flush()
#     return delta_max
