import numpy as np
import wannierberri as wberri
from wannierberri.symmetry.sawf import SymmetrizerSAWF
from wannierberri.symmetry.projections import Projection, ProjectionsSet

from irrep.bandstructure import BandStructure
bandstructure = BandStructure.from_espresso(
    prefix="../../tests/data/diamond-444/di",
    Ecut=200,
    normalize=False, include_TR=False)
spacegroup = bandstructure.spacegroup

# pos_bond = [[0,0,0]] # only one position is enouggh, the other 4 sites are generated by symmetry
pos_bond = [[0, 0, 0], [0, 0, 1 / 2], [0, 1 / 2, 0], [1 / 2, 0, 0]]  # but it is allowed to specify all 4 to preserve the order and selection of the unit cell

pos_atom = np.array([[-1, -1, -1], [1, 1, 1]]) / 8
proj_sp3 = Projection(position_num=pos_atom, orbital='sp3', spacegroup=spacegroup)


projname = 'sp3'  # choose from ['s_bond', 'p_bond', 'sp_bond', 'sp3']
projset = ProjectionsSet([proj_sp3])
froz_min = -10
froz_max = 30
win_min = -10
win_max = 1000

wandata = wberri.WannierData.from_w90_files(seedname='../../tests/data/diamond-444/diamond', files=['mmn', 'eig', 'win'])
symmetrizer = SymmetrizerSAWF.from_irrep(bandstructure)
wandata.set_symmetrizer(symmetrizer)
wandata.set_projections(projset, bandstructure=bandstructure)


wberri.wannierise(
    wandata=wandata,
    froz_min=froz_min,
    froz_max=froz_max,
    outer_min=win_min,
    outer_max=win_max,
    num_iter=100,
    conv_tol=1e-10,
    print_progress_every=20,
    sitesym=True,
    localise=True,
)

wandata.chk.write_epw_ukk("Ukk.dat")
wandata.chk.to_npz("diamond-chk.npz")
