# This tutorial shows how to generate a symmetrizer
# and then use it to generate a Wannier90 output.
# It uses Irrep, and may be used with any DFT code that is supported by Irrep (QE, VASP, AINIT, ...)

import os
import numpy as np
from wannierberri.symmetry.projections import Projection, ProjectionsSet


# for data_dir in ['diamond', 'diamond-444']:

from irrep.bandstructure import BandStructure
bandstructure = BandStructure(code='espresso',
                            prefix= "di",
                            # Ecut=200,
                            normalize=False, include_TR=False)
spacegroup = bandstructure.spacegroup

# pos_bond = [[0,0,0]] # only one position is enouggh, the other 4 sites are generated by symmetry
pos_bond = [[0, 0, 0], [0, 0, 1 / 2], [0, 1 / 2, 0], [1 / 2, 0, 0]]  # but it is allowed to specify all 4 to preserve the order and selection of the unit cell

pos_atom = np.array([[-1, -1, -1], [1, 1, 1]]) / 8
zaxis_bond = (pos_atom[1] - pos_atom[0]) @ spacegroup.lattice
proj_s_bond = Projection(position_num=pos_bond, orbital='s', spacegroup=spacegroup)
proj_sp3 = Projection(position_num=pos_atom, orbital='sp3', spacegroup=spacegroup, rotate_basis=True)
proj_p_bond = Projection(position_num=pos_bond, orbital='pz', zaxis=zaxis_bond, spacegroup=spacegroup, rotate_basis=True)


for projname in ['s_bond', 'p_bond', 'sp_bond', 'sp3']:
    if projname == 's_bond':
        projset = ProjectionsSet([proj_s_bond])
    elif projname == 'sp3':
        projset = ProjectionsSet([proj_sp3])
    elif projname == 'sp_bond':
        projset = ProjectionsSet([proj_p_bond, proj_s_bond])
    elif projname == 'p_bond':
        projset = ProjectionsSet([proj_p_bond])
    else:
        raise ValueError(f"Unknown system name: {projname}")
    file_win = open("diamond-template.win").read()
    proj_str = projset.write_wannier90(basis=True)
    with open("diamond.win", "w") as f:
        f.write(proj_str + "\n" + file_win)
    os.system(f"wannier90.x -pp diamond")
    os.system(f"pw2wannier90.x < diamond.pw2wan")
    # copy amn file
    os.system(f"mv diamond.amn diamond-{projname}.amn")
    os.system(f"mv diamond.win diamond-{projname}.win")


